-- return {
--   {
--     "nvim=treesitter/nvim-treesitter",
--     tag = "v0.9.1",
--     highlight = {enable = true},
--     opts = {
--       ensure_installed = {
--         "javascript",
--         "typescript",
--         "css",
--         "gitignore",
--         "graphql",
--         "prisma",
--         "json",
--         "vim",
--         "lua",
--         "sql",
--         "solidity",
--         "slang",
--         "python",
--         "cpp",
--       },
--       query_linter = {
--         enable = true,
--         use_virtual_text = true,
--         lint_events = { "BufWrite", "CursorHold" },
--       },
--     },
--   },
-- }
